config/routes.rb
Rails.application.routes.draw do
  root 'article#index'
  get 'article/index'
  get 'search/index'
  resources 'article', only: [:index]
  resources 'search', only: [:index]
  post 'article/search', to: 'article#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates_presence_of :title, :description
  validates :title, length: { minimum: 3, maximum: 90 }
  validates :description, length: { minimum: 10, maximum: 300 }
end

app/models/search.rb
class Search < ApplicationRecord
  validates_presence_of :query
  validates :query, length: { minimum: 3, maximum: 90 }

  def searched?(search)
    jarow = FuzzyStringMatch::JaroWinkler.create(:native)
    similarity_percentage = jarow.getDistance(search, query)
    similarity_percentage > 0.8
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def check_session
    session[:user_id] = SecureRandom.urlsafe_base64(16) if session[:user_id].nil?
  end
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
  before_action :check_session, only: [:search]

  def index
    @articles = Article.all
  end

  def search
    articles = Article.where('title LIKE ?', "%#{params[:query]}%")
    render(partial: 'articles', locals: { articles: })
    add_search_todb(params[:query], session[:user_id])
  end

  private

  def add_search_todb(query, session)
    return if query.nil? || query.length < 3

    recent_search = Search.new(user_params)
    recent_search.session_id = session
    session_search = Search.where(session_id: session).last
    if session_search.nil? || !session_search.searched?(query)
      recent_search.save
    elsif session_search.query.length < query.length
      session_search.update(query:)
    end
  end

  def user_params
    params.permit(:query)
  end

  # def check_session
  #   session[:user_id] = SecureRandom.urlsafe_base64(16) if session[:user_id].nil?
  # end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :check_session

  def index
    @user = session[:user_id]

    @session_values = Search.where(session_id: @user).pluck(:query).reverse.first(100)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/article/_articles.html.erb
<div>
  <h2>Articles</h2>
  <div class="Search__forms">
    <%= render "article/form" %>
  </div>
  <article>
    <%= turbo_frame_tag "articles" do %>
      <% articles.each do |article| %>
        <div class="article">
          <h1><%= article.title %></h1>
          <p><%= article.description %></p>
        </div>
      <% end %>
    <% end %>
  </article>
</div>

app/views/article/_form.html.erb
<%= form_with url: article_search_path, method: :post, authenticity_token: false, data: { controller: "search", search_target: "form", turbo_frame: "articles" } do |form| %>
  <%= form.text_field :query,
    placeholder: "Search by title",
    autocomplete: "off",
    data: { action: "input->search#search" }
  %>
<% end %>

app/views/article/index.html.erb
<section id="articles-section" class="article__section">
  <%= render partial: 'articles', locals: { articles: @articles } %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchAnayltics</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="nav">
      <ul>
        <li><%= link_to 'Articles', root_path %></li>
        <li><%= link_to 'Analytics', search_index_path %></li>
      </ul>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/search/index.html.erb
<section class="search__section">
  <h3>Searched Value for the current User: <%= @user %></h3>
  <div class="search__values">
    <% @session_values.each do |search| %>
    <ul>
      <li style="list_style=none"><%= search %></li>
    </ul>
    <% end %>
  </div>
</section>